# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'beca-filmes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for beca-filmes
  pod 'Alamofire', '~> 4.7.0'
  pod 'AlamofireImage', '~> 3.4.0'

end
